name: my_time_manager
description: A powerful application to manage your time
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  sqflite: ^2.0.0+2
  intl: any
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  uuid: ^3.0.7
  json_annotation: ^4.6.0
  meta: ^1.7.0
  #firebase_core: ^2.13.1
  #firebase_auth: ^4.6.2
  #google_sign_in: ^5.2.1
  shared_preferences: ^2.1.2
  sqflite_common_ffi: ^2.2.5
  path_provider: ^2.0.15
  font_awesome_flutter: ^10.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.3.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/


