name: my_time_manager
description: A powerful application to manage your time
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  sqflite: ^2.0.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
flutter:
  uses-material-design: true

