// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAkmvwpXawvtJH5LErsuAOVzLAL-O4HOCE',
//     appId: '1:243455079506:web:0f237b52542972fd2edb8b',
//     messagingSenderId: '243455079506',
//     projectId: 'my-time-manager-c6375',
//     authDomain: 'my-time-manager-c6375.firebaseapp.com',
//     storageBucket: 'my-time-manager-c6375.appspot.com',
//     measurementId: 'G-J9X112SF38',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB8UaR4A4LZWzt0l-OK-x79WbIhXd9r44U',
//     appId: '1:243455079506:android:3c5a9fa74cc5010b2edb8b',
//     messagingSenderId: '243455079506',
//     projectId: 'my-time-manager-c6375',
//     storageBucket: 'my-time-manager-c6375.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCV7lg6OvVda0CYXLDKL0Hn5roTBygG_bo',
//     appId: '1:243455079506:ios:ceef46e3d7610bf62edb8b',
//     messagingSenderId: '243455079506',
//     projectId: 'my-time-manager-c6375',
//     storageBucket: 'my-time-manager-c6375.appspot.com',
//     iosClientId: '243455079506-gs9vn6nhhs63aoqpqkhhe1e65kc4g27n.apps.googleusercontent.com',
//     iosBundleId: 'com.dienvu.myTimeManager',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCV7lg6OvVda0CYXLDKL0Hn5roTBygG_bo',
//     appId: '1:243455079506:ios:422e1384fd876b842edb8b',
//     messagingSenderId: '243455079506',
//     projectId: 'my-time-manager-c6375',
//     storageBucket: 'my-time-manager-c6375.appspot.com',
//     iosClientId: '243455079506-vkf18ht6ut8sfsofcai7kpn35o8icdhu.apps.googleusercontent.com',
//     iosBundleId: 'com.dienvu.myTimeManager.RunnerTests',
//   );
// }
